export const arrayItems = [
  {
    name: "Q&A",
    id: "q&a",
    //image: "url_to_qa_image.jpg",
    description: "Answer questions based on existing knowledge",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Grammer Correction",
    id: "grammarcorrection",
    //image: "url_to_qa_image.jpg",
    description: "Corrects sentences into standard English.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Pdf Summarise",
    id: "Pdf",
    //image: "url_to_qa_image.jpg",
    description: "Translates difficult text into simpler concepts.",
    option: {
      model: "text-davinci-003",
      temperature: 0.7,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Text to Pdf Generator",
    id: "summary",
    //image: "url_to_qa_image.jpg",
    description: "Generates a PDF from text input.",
    option: {
      model: "text-davinci-003",
      temperature: 0.3,
      max_tokens: 100,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
    {
        name: "English to other languages",
        id: "LanguageTrans",
        //image: "url_to_qa_image.jpg",
        description: "Removes Bug",
        option: {
            model: "gpt-3.5-turbo",
            temperature: 0.7,
            max_tokens: 64,
            top_p: 1,
        },
    },

  {
    name: "Explain code",
    id: "explainCode",
    //image: "url_to_qa_image.jpg",
    description: "Explain a complicated piece of code.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "JavaScript to Python",
    id: "jstopy",
    //image: "url_to_qa_image.jpg",
    description: "Convert simple JavaScript expressions into Python.",
    option: {
      model: "code-davinci-002",
      temperature: 0,
      max_tokens: 64,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    name: "Weather Forecasting",
    id: "weather",
    //image: "url_to_qa_image.jpg",
    description: "Answer questions based on the weather forecast.",
    option: {
      model: "text-davinci-003",
      temperature: 0,
      max_tokens: 100,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
];
